"""定数定義"""

# TSVファイルの必須カラム
REQUIRED_COLUMNS = [
    "競馬場",
    "開催年",
    "開催日",
    "レース番号",
    "芝ダ区分",
    "距離",
    "馬番",
    "馬名",
    "単勝オッズ",
    "人気順",
    "確定着順",
    "予測順位",
    "予測スコア",
]

# TSVカラムとモデルフィールドのマッピング
COLUMN_MAPPING = {
    "競馬場": "racecourse",
    "開催年": "year",
    "開催日": "date",
    "レース番号": "race_number",
    "芝ダ区分": "surface",
    "距離": "distance",
    "馬番": "horse_number",
    "馬名": "horse_name",
    "単勝オッズ": "win_odds",
    "人気順": "popularity",
    "確定着順": "final_rank",
    "予測順位": "predicted_rank",
    "予測スコア": "predicted_score",
    "複勝1着馬番": "place_1st_horse",
    "複勝1着オッズ": "place_1st_odds",
    "複勝1着人気": "place_1st_popularity",
    "複勝2着馬番": "place_2nd_horse",
    "複勝2着オッズ": "place_2nd_odds",
    "複勝2着人気": "place_2nd_popularity",
    "複勝3着馬番": "place_3rd_horse",
    "複勝3着オッズ": "place_3rd_odds",
    "複勝3着人気": "place_3rd_popularity",
    "馬連馬番1": "bracket_horse1",
    "馬連馬番2": "bracket_horse2",
    "馬連オッズ": "bracket_odds",
    "ワイド1_2馬番1": "wide_1_2_horse1",
    "ワイド1_2馬番2": "wide_1_2_horse2",
    "ワイド2_3着馬番1": "wide_2_3_horse1",
    "ワイド2_3着馬番2": "wide_2_3_horse2",
    "ワイド1_3着馬番1": "wide_1_3_horse1",
    "ワイド1_3着馬番2": "wide_1_3_horse2",
    "ワイド1_2オッズ": "wide_1_2_odds",
    "ワイド2_3オッズ": "wide_2_3_odds",
    "ワイド1_3オッズ": "wide_1_3_odds",
    "馬単馬番1": "exacta_horse1",
    "馬単馬番2": "exacta_horse2",
    "馬単オッズ": "exacta_odds",
    "３連複オッズ": "trio_odds",
}
